# Basic
title: Weaving Wong
subtitle: 总觉得该写点啥...
welcome_message: 分享读书、学习、生活感悟
description: 嗨，我是Weaving，一名机器学习爱好者.
creator: <a href="https://WeavingWong.github.io">@Weaving</a>

url: "https://WeavingWong.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的github主页, url: 'https://github.com/WeavingWong'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: WeavingWong
    # duoshuo: 
    
social:
    weibo: WeavingWong
    github: WeavingWong
    twitter: weaving_wong
    # gplus: 107108267983477358170
    mail: weaving.wong@gmail.com

# Google Analytics
ga:
    id: UA-143613699-1
    host: https://WeavingWong.github.io

